/**
 * markdownReporter.js
 * Writes a human-readable REPORT.md file from test results.
 */

import { writeFileSync } from "fs";
import { resolve } from "path";

/**
 * Generates REPORT.md in the current working directory.
 * @param {import('../testEndpoint.js').EndpointResult[]} results
 */
export async function generateMarkdownReport(results) {
  const total = results.length;
  const passed = results.filter((r) => r.passed).length;
  const failed = total - passed;
  const successRate =
    total > 0 ? `${Math.round((passed / total) * 100)}%` : "N/A";
  const avgResponseTime =
    total > 0
      ? Math.round(results.reduce((sum, r) => sum + r.responseTime, 0) / total)
      : 0;
  const generatedAt = new Date().toLocaleString("en-GB", { timeZone: "UTC" }) + " UTC";

  const lines = [
    `# 🛡️ API Sentinel — Report`,
    ``,
    `> Generated: **${generatedAt}**`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `| Metric             | Value            |`,
    `|--------------------|------------------|`,
    `| Total endpoints    | ${total}                |`,
    `| ✅ Passed          | ${passed}                |`,
    `| ❌ Failed          | ${failed}                |`,
    `| Success rate       | ${successRate}            |`,
    `| Avg response time  | ${avgResponseTime}ms            |`,
    ``,
    `---`,
    ``,
    `## Results`,
    ``,
    `| Name | Method | URL | Expected | Got | Time | Status |`,
    `|------|--------|-----|----------|-----|------|--------|`,
    ...results.map((r) => {
      const statusIcon = r.passed ? "✅" : "❌";
      const got = r.status !== null ? String(r.status) : "—";
      const errNote = r.error ? ` ⚠️ ${r.error}` : "";
      return `| ${r.name} | \`${r.method}\` | ${r.url} | ${r.expectedStatus} | ${got} | ${r.responseTime}ms | ${statusIcon}${errNote} |`;
    }),
    ``,
    `---`,
    ``,
    `*Generated by [api-sentinel](https://github.com/Ezeril/api-sentinel)*`,
  ];

  const outputPath = resolve(process.cwd(), "REPORT.md");
  writeFileSync(outputPath, lines.join("\n"), "utf-8");
}
